### PR TITLE
fixed IsAlive calculation in FbConnectionPoolManager.Pool.IsAlive

### PR DESCRIPTION
**Pull request by realic**
Hey Jiri
I found an error in version 5.12.0. I believe it was introduced when fixing DNET-787. 

Please advise if the unittest is not implementet in a way you like.

### CODE REVIEW

**Comment by cincuranet** [comment]
Fix the PR to not have unnecessary changes, please.

**Comment by realic** [comment]
Do you want me to extract the IsAlive and GetTicks to a seperate publice testable class?

**Comment by cincuranet** [comment]
Yes. I would put into `Common` something like `ConnectionLifetimeHelper` (internal), with `IsAlive` method. And I would test this. The `GetTicks` is not needed.

**Comment by realic** [comment]
The requested changes have been implemented, if you haven't already received a notification about it.

**Comment by cincuranet** [comment]
Merged by 138a347f0f3c19a0ff9b39d3cdd94a002d3b1b8c.

**Pull request closed without merging**
