### PR TITLE
Implemented Scaffolding, Added Blob Mapping from Db to Model

### PR DESCRIPTION
**Pull request by pgiacomo69**
Implemented Scaffolding, Added Blob Mapping from Db to Model

### CODE REVIEW

**Comment by cincuranet** [comment]
Can you add/extract the blob mapping into separate PR and maybe use `BLOB SUB_TYPE BINARY` instead of number?

**Comment by pgiacomo69** [comment]
ok

> Il giorno 7 giu 2020, alle ore 20:04, Jiri Cincura ↹ <notifications@github.com> ha scritto:
> 
> Can you add/extract the blob mapping into separate PR and maybe use BLOB SUB_TYPE BINARY instead of number?

**Comment by cincuranet** [comment]
You don't have to close this one. Just the one change into separate PR, rest can stay.

**Comment by pgiacomo69** [comment]
Done,
sorry but I’m not a git expert, I preferred to pull down the entire fork, I will push other modifications one by one.I think  I’ve to study how to work with branches.

**Pull request closed without merging**
