### PR TITLE
Ef scaffolding

### PR DESCRIPTION
**Pull request by pgiacomo69**
Scaffolding Implemented for Database First,

### CODE REVIEW

**Comment by cincuranet** [comment]
Can you remove commits that are related to EF Core 5 and keep only the scaffolding changes?

**Comment by pgiacomo69** [comment]
Ok, 

> Can you remove commits that are related to EF Core 5 and keep only the scaffolding changes?

Done, now Scaffolding works only with NetStandard2.0
In 5.0 it throws a 
"Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.DecimalTypeMapping..ctor(System.String, System.Nullable`1<System.Data.DbType>)'." exception.

**Comment by pgiacomo69** [comment]
I'm keeping another branch with 5.0 Support, since I'm actively using it on a project. Have you tought how to handle 5.0 support? Should I make another pull request  (after you merge this, eventually) or are you going in another direction?

**Comment by cincuranet** [comment]
Where's the `_logger` assigned?

**Comment by cincuranet** [comment]
Thanks. Merged via 88da531.

**Comment by pgiacomo69** [comment]
Thanks to you! 
I forgot _logger there after a test, sorry

**Comment by cincuranet** [comment]
It can stay. No problem with that. I just fixed the ctor in `618a3010894dcf6c5a5b88b99a14d3d23e2d38ec`.

**Pull request closed without merging**
