### PR TITLE
Map TIME to System.TimeSpan.

### PR DESCRIPTION
**Pull request by siegfriedpammer**
Second part of #86

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Looks like the build break is unrelated to my change.

**Comment by cincuranet** [comment]
Re-triggered [here](https://dev.azure.com/FirebirdClient/CI/_build/results?buildId=1147).

**Comment by cincuranet** [comment]
Now it looks like it's related. The `FunctionalTests` did not finish executing, the [final summary is missing](https://dev.azure.com/FirebirdClient/CI/_build/results?buildId=1141&view=logs&jobId=e7916197-3236-5978-5a2f-0ccb55475459&taskId=24cd0711-c6e8-5994-3c7d-96742b13b8fc&lineStart=825&lineEnd=825&colStart=1&colEnd=58), though it's not visible what failed. Maybe it crashed hard.

**Comment by siegfriedpammer** [comment]
I think I will have to figure out how to run the tests on my machine... any special prerequisites necessary?

**Comment by cincuranet** [comment]
[This](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/blob/master/Provider/tests.ps1) is how the tests are executed. You can use the script directly or you can just use part for manual execution (in case you set up your environment manually).

**Comment by cincuranet** [comment]
OK, looks like it's me how is going to debug it.

Done in 63e52971.

**Comment by siegfriedpammer** [comment]
I am sorry for not being able to get to this! Thank you very much for fixing this and accepting my contribution.

**Pull request merged**
